- hosts: mysql
  vars_files:
    - vars/tcg.yml
  roles:
#    - role: mysql_ext_volume
    - role: mysql
      mysql_root_password: De8ahgahhohhieCapaiM
    - role: tcg_db

- hosts: tcg
  vars_files:
    - vars/tcg.yml
  roles:
    - role: tcg
